# Pandas

This week we are introduing [Pandas](https://pandas.pydata.org/), which we will then follow up on in Week 8. Pandas is the Python equivalent of R's Data Frames, and is used for data in tabular form. Pandas is built on NumPy but is better for dealing with datasets.

Its not clear why its called Pandas, but apparently people usually say the name refers to 'Python ANd DAta analysiS' or 'PANel DAta'.

## Pandas Series

Let try a quick example. This following data is taken from the UK General Election Results in 2019. Let start by creating a simple series for the number of seats each party won.

In [1]:
import pandas as pd
import numpy as np
seats = np.array([265, 203, 48, 11, 8])
votes = pd.Series(seats)
votes

0    265
1    203
2     48
3     11
4      8
dtype: int64

This isnt very clear right now, the row names arent very descriptive of what the dataset is about.

In [2]:
votes.index

RangeIndex(start=0, stop=5, step=1)

Let's add some row names

In [3]:
parties = np.array(['Conservatives', 'Labour', 'SNP', 'Liberal Democrat', 'DUP'])
votes.index = parties
print(votes.index)
print(' ') # just to print a blank line
votes

Index(['Conservatives', 'Labour', 'SNP', 'Liberal Democrat', 'DUP'], dtype='object')

Conservatives       265
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
dtype: int64

Or we could have recreated the dataset as follows

In [4]:
votes = pd.Series(seats, index=parties)
votes

Conservatives       265
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
dtype: int64

Oops, I somehow missed out on the votes for others. Others should have 15 votes. Let's add that

In [5]:
votes['Other'] = 15
votes

Conservatives       265
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15
dtype: int64

Oops, I somehow (deliberately) make an error for the number of votes the Conservatives got during the election. It should be 365, not 265, let's change that

In [6]:
votes['Conservatives'] = 365
votes

Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15
dtype: int64

We can add a name for our Series. It doesn't come up where we are expecting it to, but it will when we look at Data Frames

In [7]:
votes.name = 'Seats'
votes

Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15
Name: Seats, dtype: int64

We can also create this from scratch

In [8]:
parties = np.array(['Conservatives', 'Labour', 'SNP', 'Liberal Democrat', 'DUP', 'Other'])
seats = np.array([365, 203, 48, 11, 8, 15])
votes = pd.Series(seats, index=parties, name='Seats')
votes

Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15
Name: Seats, dtype: int64

## Extracting Information from Pandas Series

Lets start by getting some summaries of the information in our series

In [9]:
print(votes.sum())
print(votes.std())
print(votes.var())
print(votes.min())
print(votes.max())

650
146.10361619982808
21346.26666666667
8
365

Let's find out how many seats the SNP got and what proportion of the seats that is

In [10]:
print(votes['SNP'])
votes['SNP']/votes.sum()

48

np.float64(0.07384615384615385)

Let's also find out how many seats Labour have but using the row index this time. Remembering Python is zero indexed, this is the 2nd row or index 1

In [11]:
votes.iloc[1]

np.int64(203)

# Pandas Data Frame

It would also be useful to add the change in the number of seats since the last election each party has seen. However in order to do that we need to change from a Series to a Data Frame. There is a method to do this, although I'm not sure whether it is in the notes.

In [12]:
votes.to_frame()

                  Seats
Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15

However let's start where we were before so we can see the difference between Series and Data Frames

In [13]:
seats = np.array([265, 203, 48, 11, 8])
parties = np.array(['Conservatives', 'Labour', 'SNP', 'Liberal Democrat', 'DUP'])
data = {'Seats': seats}
votes = pd.DataFrame(data, index = parties)
votes

                  Seats
Conservatives       265
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8

Once again we are missing a row for 'Other' and we have put the number of seats in incorrectly for the 'Conservatives'. But lets's just fix the Conservative votes for now

In [14]:
votes.loc['Conservatives'] = 365
votes

                  Seats
Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8

And let's add a row for how the number of seats has changed since the last election

In [15]:
change = np.array([47, -59, 13, -1, -2])
votes['Change'] = change
votes

                  Seats  Change
Conservatives       365      47
Labour              203     -59
SNP                  48      13
Liberal Democrat     11      -1
DUP                   8      -2

Let's add that row back in for 'Other' now. There are a few different ways of doing this...

In [16]:
other_data = pd.DataFrame({'Seats': 15, 'Change': 2}, index=['Other'])
votes = pd.concat([votes, other_data])
votes

                  Seats  Change
Conservatives       365      47
Labour              203     -59
SNP                  48      13
Liberal Democrat     11      -1
DUP                   8      -2
Other                15       2

Lets add a column for the percentage of seats each party has. To so that we need to do a summary on one of the columns

In [17]:
total_seats = votes.sum().iloc[0]
perc_seats = votes['Seats'] / total_seats * 100
votes['Percentage Seats'] = perc_seats
votes

                  Seats  Change  Percentage Seats
Conservatives       365      47         56.153846
Labour              203     -59         31.230769
SNP                  48      13          7.384615
Liberal Democrat     11      -1          1.692308
DUP                   8      -2          1.230769
Other                15       2          2.307692

We could also create all this dataset from scratch using the following code

In [18]:
votes.Seats

Conservatives       365
Labour              203
SNP                  48
Liberal Democrat     11
DUP                   8
Other                15
Name: Seats, dtype: int64

In [19]:
parties = np.array(['Conservatives', 'Labour', 'SNP', 'Liberal Democrat', 'DUP', 'Other'])
seats = np.array([365, 203, 48, 11, 8, 15])
change = np.array([47, -59, 13, -1, -2, 2])
total_seats = votes.sum()[0]
perc_seats = votes['Seats'] / total_seats * 100
votes = pd.DataFrame({'Seats': seats, 'Changes': change, 'Percentage Seats': perc_seats}, index=parties)
votes

/tmp/ipython-input-676912909.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  total_seats = votes.sum()[0]

                  Seats  Changes  Percentage Seats
Conservatives       365       47         56.153846
Labour              203      -59         31.230769
SNP                  48       13          7.384615
Liberal Democrat     11       -1          1.692308
DUP                   8       -2          1.230769
Other                15        2          2.307692

## Premier League Data

Apologies for those that aren't football fan... The dataset [premierleague.csv](https://github.com/UofGAnalyticsData/DPIP/blob/main/colab_datasets/premierleague.csv) gives the up to date English Premier League football table (as off 09/11/2021). Lets load it in and have a look!

Its easier to download the code from Giuthub when working with Google Colabs. But the normal code is commented out. To get the relevant code off GitHub, go to the link above and just above the dataset to the right click 'raw', then copy the link out of the browser bar

In [20]:
# file_path = 'C:\\Users\\Vinny\\teaching\\DPIP\\colab_datasets\\premierleague.csv'
# football = pd.read_csv(file_path)
url = 'https://raw.githubusercontent.com/UofGAnalyticsData/DPIP/main/colab_datasets/premierleague.csv'
football = pd.read_csv(url)
football.head()

              Team  Pl  W  D  L   F   A  GD  Pts
0          Chelsea  11  8  2  1  27   4  23   26
1  Manchester City  11  7  2  2  22   6  16   23
2  West Ham United  11  7  2  2  23  13  10   23
3        Liverpool  11  6  4  1  31  11  20   22
4          Arsenal  11  6  2  3  13  13   0   20

It might be easier to set the team as the Index, so lets do that

In [21]:
football = football.set_index('Team')
football.head()

                 Pl  W  D  L   F   A  GD  Pts
Team
Chelsea          11  8  2  1  27   4  23   26
Manchester City  11  7  2  2  22   6  16   23
West Ham United  11  7  2  2  23  13  10   23
Liverpool        11  6  4  1  31  11  20   22
Arsenal          11  6  2  3  13  13   0   20

Lets get the shape of the Data Frame and extract the row for 'Manchester United' and column for points ('Pts')

In [22]:
print(football.shape)
print(' ') # just adding a row of white space
print(football.loc['Manchester United'])
print(' ')
football['Pts']

(20, 8)

Pl     11
W       5
D       2
L       4
F      19
A      17
GD      2
Pts    17
Name: Manchester United, dtype: int64

Team
Chelsea                     26
Manchester City             23
West Ham United             23
Liverpool                   22
Arsenal                     20
Manchester United           17
Brighton and Hove Albion    17
Wolverhampton Wanderers     16
Tottenham Hotspur           16
Crystal Palace              15
Everton                     15
Leicester City              15
Southampton                 14
Brentford                   12
Leeds United                11
Aston Villa                 10
Watford                     10
Burnley                      8
Newcastle United             5
Norwich City                 5
Name: Pts, dtype: int64